### PR TITLE
IFS: Add image version info to logging

### PR DESCRIPTION
**Pull request by AthenasJimenez**
Signed-off-by: Athenas Jimenez <athenas.jimenez.gonzalez@intel.com>

### CODE REVIEW

**Review by thiagomacieira — DISMISSED** [review]
Good. Since it's going to later conflict with #163, can you add there the printing of the version number and the chunk number to the `log_error`?

Would be nice to know if the IFS engineers prefer version numbers in hex.

**Comment by AthenasJimenez** [comment]
Yes. I'll rebase this change in #163 and add the chunk number as well.

Regarding to use "log_error", I don't agree. As I see it, we should log image version and chunk number on info always. In other words, no matter if we have a pass or fail, version and chunk number are present in logs.

**Comment by thiagomacieira** [comment]
> Yes. I'll rebase this change in #163 and add the chunk number as well.
> 
> Regarding to use "log_error", I don't agree. As I see it, we should log image version and chunk number on info always. In other words, no matter if we have a pass or fail, version and chunk number are present in logs.

Agreed then. But it should be on the error message too, because on lower-verbosity outputs, the `log_info` won't be present.

**Comment by AthenasJimenez** [comment]
Got it. I just updated the log error to include image version.

**Comment by AthenasJimenez** [comment]
This change is no longer needed. Changes were addressed by #163

**Pull request closed without merging**
